/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

/**
 *
 * @author biiel
 */
public class AbrirCaixa extends javax.swing.JFrame {

    /**
     * Creates new form AbrirCaixa
     */
    private final Erro ERRO = new Erro();
    private final Arquivo ARQUIVO;
    private TelaInicial principal;    

    public AbrirCaixa(Arquivo arq) {
        initComponents();
        this.ARQUIVO = arq;
        
    }

    public void confirma(TelaInicial confirm) { //retorno da tela inicial, pra salvar corretamente
        this.principal = confirm;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDinheiro = new javax.swing.JLabel();
        tfDinheiro = new javax.swing.JTextField();
        tfSalgados = new javax.swing.JTextField();
        txtSalgados = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDinheiro.setText("Valor inicial em dinheiro:");

        tfDinheiro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDinheiroKeyTyped(evt);
            }
        });

        tfSalgados.setText("0");
        tfSalgados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalgadosKeyTyped(evt);
            }
        });

        txtSalgados.setText("Quantidade de salgados:");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSalgados)
                            .addComponent(tfSalgados, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDinheiro)
                            .addComponent(tfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btCancelar)
                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtDinheiro)
                .addGap(18, 18, 18)
                .addComponent(tfDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSalgados)
                .addGap(18, 18, 18)
                .addComponent(tfSalgados, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btSalvar)
                .addGap(18, 18, 18)
                .addComponent(btCancelar)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Produto prod;
        
        String dinheiro = tfDinheiro.getText();
        String salgados = tfSalgados.getText();
        
        int virgulaD = dinheiro.indexOf(",");
        int virgulaS = salgados.indexOf(",");
        
        boolean validacao = true; 

        // Validar o valor inserido        
        if (dinheiro.isEmpty() || dinheiro.isBlank() || virgulaD!=-1){
            validacao = false;
            ERRO.erro("Erro de Preenchimento", "Digite valores válidos", "erro");
            tfDinheiro.setText("");
        }
        
        // Validar a quantidade de salgados inserida
        if (salgados.isEmpty() || salgados.isBlank() || virgulaS!=-1 || !salgados.matches("\\d+")){
            validacao = false;
            ERRO.erro("Erro de Preenchimento", "Digite valores válidos", "erro");
            tfSalgados.setText("");
        }        
        
        if (principal != null && validacao) {
            prod = ARQUIVO.getProduto(0);
            prod.setQuantidade(Integer.parseInt(tfSalgados.getText()));
            
            ARQUIVO.edita(prod);                        
            ARQUIVO.adiciona(Double.parseDouble(tfDinheiro.getText()), "=");            
            
            principal.iniciarCaixa();
            this.dispose();
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tfDinheiroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDinheiroKeyTyped
        String caracteres = "0987654321.";
        if (!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_tfDinheiroKeyTyped

    private void tfSalgadosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalgadosKeyTyped
        String caracteres = "0987654321";
        if (!caracteres.contains(evt.getKeyChar()+"")){
            evt.consume();
        }
    }//GEN-LAST:event_tfSalgadosKeyTyped

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JTextField tfDinheiro;
    private javax.swing.JTextField tfSalgados;
    private javax.swing.JLabel txtDinheiro;
    private javax.swing.JLabel txtSalgados;
    // End of variables declaration//GEN-END:variables
}
