/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programa;

import java.util.ArrayList;

/**
 *
 * @author biiel
 */
public class Pagamento extends javax.swing.JFrame {

    private final ArrayList<Pessoa> NOMES;
    private final Erro ERRO = new Erro();
    private final Arquivo ARQUIVO;
    private String nome;    

    /**
     * Creates new form Pagamento
     * @param arq
     */
    public Pagamento(Arquivo arq) {
        initComponents();
        this.ARQUIVO = arq;
        NOMES = arq.getPessoas();
        NOMES.forEach((p) -> {
            cbNomesFiado.addItem(p.getNome());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbNomesFiado = new javax.swing.JComboBox<>();
        tfSaldoDevedor = new javax.swing.JTextField();
        jlSaldo = new javax.swing.JLabel();
        btReceber = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbNomesFiado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbNomesFiadoItemStateChanged(evt);
            }
        });

        jlSaldo.setText("Saldo devedor a ser pago:");

        btReceber.setText("RECEBER");
        btReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReceberActionPerformed(evt);
            }
        });

        btCancelar.setText("CANCELAR");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlSaldo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbNomesFiado, 0, 200, Short.MAX_VALUE)
                                .addComponent(tfSaldoDevedor))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cbNomesFiado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jlSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfSaldoDevedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(btReceber)
                .addGap(26, 26, 26)
                .addComponent(btCancelar)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReceberActionPerformed
        if (ARQUIVO.atualizaSaldo(nome, -Double.parseDouble(tfSaldoDevedor.getText()))){
            ERRO.erro("Atualização de Saldo", "Atualização de saldo feita com sucesso", "info");            
        } else {
            ERRO.erro("Pagamento adicional", "O valor inserido é maior do que o saldo devedor", "erro");
        }
        this.dispose();
    }//GEN-LAST:event_btReceberActionPerformed

    private void cbNomesFiadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbNomesFiadoItemStateChanged
        for (Pessoa p : NOMES) {
            if (cbNomesFiado.getSelectedItem().equals(p.getNome())) {                
                tfSaldoDevedor.setText(p.getSaldo().toString());
                nome = cbNomesFiado.getSelectedItem().toString();
            }
        }
    }//GEN-LAST:event_cbNomesFiadoItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btReceber;
    private javax.swing.JComboBox<String> cbNomesFiado;
    private javax.swing.JLabel jlSaldo;
    private javax.swing.JTextField tfSaldoDevedor;
    // End of variables declaration//GEN-END:variables
}
